artikel/urls.py
from django.conf.urls import url


from .views import (
    ArtikelListView,
    ArtikelDetailView,
    ArtikelCreateView,
    ArtikelManageView,
    ArtikelUpdateView,
    ArtikelDeleteView
)

app_name = 'artikel'

urlpatterns = [

                  url(r'^$', ArtikelListView.as_view(), name='list'),
                  url(r'^tambah/$', ArtikelCreateView.as_view(), name='create'),
                  url(r'^manage/update/(?P<pk>\d+)$', ArtikelUpdateView.as_view(), name='update'),
                  url(r'^manage/delete/(?P<pk>\d+)$', ArtikelDeleteView.as_view(), name='delete'),
                  url(r'^manage/$', ArtikelManageView.as_view(), name='manage'),
                  url(r'^detail/(?P<slug>[\w-]+)$', ArtikelDetailView.as_view(), name='detail'),
              ]

blog/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from .views import BlogHomeView

urlpatterns = [
                  url(r'^artikel/', include('artikel.urls', namespace='artikel')),
                  url(r'^login/', include('login.urls', namespace='login')),
                  url(r'^$', BlogHomeView.as_view(), name='home'),
                  url(r'^admin/', admin.site.urls),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.conf.urls import url 
from .views import loginView,logoutView

app_name = 'login'

urlpatterns = [
    
    url(r'^$', loginView, name="login"),
	url(r'^logout/$', logoutView, name="logout")
]

artikel/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse


# Create your models here.
class Artikel(models.Model):
    judul = models.CharField(max_length=255)
    isi = models.TextField()
    kategori = models.CharField(max_length=255)
    published = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(blank=True, editable=False)
    gambar = models.FileField()

    def save(self):
        self.slug = slugify(self.judul)
        super().save()

    def get_absolute_url(self):
        url_slug = {'slug': self.slug}
        return reverse("artikel:detail", kwargs=url_slug)

    def __str__(self):
        return "{}. {}".format(self.id, self.judul)

login/models.py
from django.db import models

# Create your models here.

artikel/forms.py
from django.forms import ModelForm
from django import forms
from .models import Artikel


class ArtikelForm(forms.Form,ModelForm):
    class Meta:
        model = Artikel
        fields = [
            'judul',
            'isi',
            'kategori',
            'gambar'
        ]

artikel/views.py
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.shortcuts import render
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
# from .models import Upload

from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from django.urls import reverse_lazy

# load model
from .models import Artikel
from .forms import ArtikelForm


class ArtikelPerKategori:
    model = Artikel

    def get_latest_artikel_each_kategori(self):
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
        queryset = []

        for kategori in kategori_list:
            artikel = self.model.objects.filter(kategori=kategori).latest('published')
            queryset.append(artikel)
        return queryset


class ArtikelListView(ListView):  # method controller for view
    model = Artikel  # model
    template_name = "artikel/artikel_list.html"  # view location template
    context_object_name = "artikels"  # variabel array
    ordering = ['-published']  # ordering (- desc)

    # paginate_by = 3 #limit

    def get_context_data(self, *args, **kwargs):
        kategori_list = self.model.objects.values_list('kategori', flat=True).distinct()
        self.kwargs.update({'kategori_list': kategori_list})
        kwargs = self.kwargs
        return super().get_context_data(*args, **kwargs)


class ArtikelDetailView(DetailView):
    model = Artikel
    template_name = "artikel/artikel_detail.html"
    context_object_name = "artikel"


@method_decorator(login_required, name='dispatch')
class ArtikelManageView(ListView):
    model = Artikel
    template_name = "artikel/artikel_manage.html"
    context_object_name = "artikel"


@method_decorator(login_required, name='dispatch')
class ArtikelCreateView(SuccessMessageMixin, CreateView):
    form_class = ArtikelForm
    template_name = "artikel/artikel_create.html"
    success_message = " Artikel created successfully"
    success_url = reverse_lazy('artikel:manage')


@method_decorator(login_required, name='dispatch')
class ArtikelDeleteView(SuccessMessageMixin, DeleteView):
    model = Artikel
    form_class = ArtikelForm
    template_name = "artikel/artikel_delete_confirm.html"
    danger_message = " deleted  successfully"
    success_url = reverse_lazy('artikel:manage')

    def delete(self, request, *args, **kwargs):
        messages.info(self.request, self.danger_message)
        return super(ArtikelDeleteView, self).delete(request, *args, **kwargs)


class ArtikelUpdateView(SuccessMessageMixin, UpdateView):
    form_class = ArtikelForm
    model = Artikel
    success_message = " updated created successfully"
    template_name = "artikel/artikel_update.html"

blog/views.py
from django.views.generic import TemplateView
from artikel.views import ArtikelPerKategori
from django.contrib.auth import authenticate, login, logout


class BlogHomeView(TemplateView, ArtikelPerKategori):
    template_name = "index.html"

    def get_context_data(self):
        querysets = self.get_latest_artikel_each_kategori()
        context = {
            'latest_artikel_list': querysets,

        }

        return context

login/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib import messages


def loginView(request):
    user = None
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)

        if form.is_valid():
            username_login = request.POST['username']
            password_login = request.POST['password']
            user = authenticate(request, username=username_login, password=password_login)

            if user is not None:
                login(request, user)
                messages.success(request, 'Log In successfully.')
                return redirect('../')

            else:
                messages.error(request, 'Error Log In')
        else:
            messages.error(request, 'Error Log In')

    form = AuthenticationForm(request)
    return render(request, 'login.html')


@login_required()
def logoutView(request):
    if request.method == "POST":
        if request.POST["logout"] == "Submit":
            logout(request)
            return redirect('home')

    return render(request, 'logout.html')

artikel/templates/artikel/artikel_create.html
{% extends "base.html" %}

{% block page_title %}
  Create
{% endblock page_title %}

{% block contents %}
  <div class="mt-5"></div>
  <!-- <div class="row"> -->
    <h2>Create Articles</h2>

    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        <label for="{{ form.judul.id_for_label }}">{{ form.judul.label }}</label>
        <input type="text" class="form-control" name="{{ form.judul.name }}" id="{{ form.judul.id_for_label }}" autocomplete="off"  required> 
      </div>
      <div class="form-group">
        <label for="{{ form.isi.id_for_isi }}"> {{ form.isi.label }} </label>
          <label for="{{ form.isi.id_for_label }}"> </label>
          <textarea class="form-control" id="{{ form.isi.id_for_label }}" name="{{ form.isi.name }}"></textarea>
      </div>
      <div class="form-group">
        <label for="{{ form.kategori.id_for_label }}">{{ form.kategori.label }}</label>
        <input type="text" class="form-control" name="{{ form.kategori.name }}" id="{{ form.kategori.id_for_label }}" required> 
      </div>
      <div class="form-group">
        <label for="{{ form.gambar.id_for_label }}">{{ form.gambar.label }}</label>
        <input type="file" class="form-control" name="{{ form.gambar.name }}" id="{{ form.gambar.id_for_label }}" >
      </div>

      <hr>
      <button class="btn btn-primary" type="submit"> Simpan </button>
    </form>    
  <!-- </div> -->
  
{% endblock contents %}

artikel/templates/artikel/artikel_delete_confirm.html
{% extends "base.html" %}

{% block page_title %}
  Delete ? 
{% endblock page_title %}


{% block contents %}
  <h1>Delete Article Confirmation</h1>
  <p>Apakah benar anda ingin menghapus artikel berikut : </p>
  <h3>{{ artikel.judul }}</h3>
  <form method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-sm btn-outline-primary"> Ya </button>
    <a href="{% url 'artikel:manage' %}" class="btn btn-sm btn-outline-warning"> Tidak </a>

  </form>
{% endblock contents %}

artikel/templates/artikel/artikel_detail.html
{% extends "base.html" %}

{% block page_title %}
  {{ artikel.judul }}
{% endblock page_title %} 

{% block contents %}
    <div class="mt-5"></div>
    <h1>{{ artikel.judul }}</h1>
    <h6>{{ artikel.published }}</h6>
    <hr>
    <img src="{{ artikel.gambar.url }}" alt="" width="100%" class="rounded-lg">
    <p>{{ artikel.isi }}</p>
{% endblock contents %} 

artikel/templates/artikel/artikel_list.html
{% extends "base.html" %}
{% block page_title %}
  Artikel
{% endblock page_title %}

{% block contents %}

<h2 class="mt-4 mb-4">Artikel</h2>
<div class="row">
  <div class="col-md-10">
    <div class="row">
      {% for artikel in artikels  %}
        <div class="col-md-4 mb-4">
          <div class="card">
            <img src="{{ artikel.gambar.url }}" width="100%" alt="" class="img-rounded" style="object-fit: cover; height: 200px;">
            <div class="card-body">
              <small>{{ artikel.kategori }}</small>
              <h5 class="card-title"><a href="{% url 'artikel:detail' artikel.slug %}"> {{ artikel.judul }} </a></h5>
              <small>{{ artikel.published }}</small>
              <hr>
              <small class="card-text">
                  {{ artikel.isi|truncatewords:30 }}
                  <a href="{% url 'artikel:detail' artikel.slug %}"> Selengkapnya </a>
              </small>
            </div>
          </div>
        </div>
      {% endfor %}
  </div>
</div>
  <div class="col-md-2">
    <h3>Kategori </h3> 
    <ul class="list-group">
    
      {% for kategori in kategori_list %}
      <li class="list-group-item "> <h5> <span class="badge badge-warning"> {{ kategori }} </span> </h5> </li>
      {% endfor %}
    </ul>
 
  </div>

</div>

{% endblock contents %}

artikel/templates/artikel/artikel_manage.html
{% extends "base.html" %}

{% block page_title %}
Manage
{% endblock page_title %}

{% block contents %}
<div class="mt-5"></div>
<h2>Manage</h2>

{% if messages %}
  {% for message in messages %}
          <div class="alert {% if message.tags %}alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}" role="alert">{{ message }}</div>
  {% endfor %}
{% endif %}



<a href="{% url 'artikel:create' %}" class="btn btn-primary mt-3 mb-3"> Tambah </a>
<table class="table table-hover">
  <tr>
    <th>No.</th>
    <th>Category</th>
    <th>Title</th>
    <th>Published</th>
    <th>Action</th>
  </tr>
  {% for value in artikel %}
  <tr>
    <td> {{ forloop.counter }} </td>
    <td> {{ value.kategori }} </td>
    <td> {{ value.judul }} </td>
    <td> {{ value.published }}</td>
    <td>
      <a href="{% url 'artikel:update' value.id  %}" class="btn btn-sm btn-warning"> Edit </a>
      <a class="btn btn-sm btn-danger" href="{% url 'artikel:delete' value.id  %}">Delete</a>
    </td>
  </tr>
  {% endfor %}
</table>

{% endblock contents %}

artikel/templates/artikel/artikel_update.html
{% extends "base.html" %}

{% block page_title %}
    Update
{% endblock page_title %}

{% block contents %}
    <div class="mt-5"></div>
    <h2>Update Articles</h2>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.judul.id_for_label }}">{{ form.judul.label }}</label>
            <input type="text" class="form-control" name="{{ form.judul.name }}" value="{{ artikel.judul }}"
                   id="{{ form.judul.id_for_label }}" autocomplete="off" required>
        </div>
        <div class="form-group">
            <label for="{{ form.isi.id_for_isi }}"> {{ form.isi.label }} </label>
            <textarea class="form-control" id="{{ form.isi.id_for_isi }}"
                      name="{{ form.isi.name }}"> {{ artikel.isi }} </textarea>
        </div>
        <div class="form-group">
            <label for="{{ form.kategori.id_for_label }}">{{ form.kategori.label }}</label>
            <input type="text" class="form-control" name="{{ form.kategori.name }}"
                   id="{{ form.kategori.id_for_label }}" value="{{ artikel.kategori }}" required>
        </div>
        <div class="form-group">
            <label for="{{ form.gambar.id_for_label }}">{{ form.gambar.label }} :   </label>
            <input type="file" class="form-control" name="{{ form.gambar.name }}" id="{{ form.gambar.id_for_label }}"
                   required>
        </div>

        <img src="{{ artikel.gambar.url }}" alt="{{ artikel.gambar.name }}" width="200px">


        <hr>
        <button class="btn btn-primary" type="submit"> Update</button>
    </form>
    <!-- </div> -->

{% endblock contents %}

login/templates/login.html
{% extends "base.html" %}
{% block page_title %}
    <h2> Masuk </h2>
{% endblock page_title %}

{% block contents %}

    <div class="row mt-5">
        <div class="col-md-6 offset-3">
            <div class="card">
                <div class="card-body">
                    {% if messages %}
                        {% for message in messages %}
                                <div class="alert {% if message.tags %}alert-{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}danger{% else %}{{ message.tags }}{% endif %}{% endif %}" role="alert">{{ message }}</div>
                        {% endfor %}
                    {% endif %}

                    <h5 class="card-title">Masuk</h5>
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input id="username" class="form-control" type="text" name="username" autocomplete="off">
                        </div>
                        <div class="form-group">
                            <label for="password">Password</label>
                            <input id="password" class="form-control" type="password" name="password">
                        </div>
                        <button class="btn btn-primary" type="submit" name="submit"> Masuk </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock contents %}

login/templates/logout.html
{% extends "base.html" %}
{% block page_title %}
  Logout
{% endblock page_title %}

{% block contents %}
  <div class="row mt-5">
      <p>Anda yakin ingin keluar ? </p> <br>
      <hr>
      <form method="POST">
          {% csrf_token %}
          <input type="submit" name="logout"  class="btn btn-danger"  >  
          <a href="{% url 'home' %}"   class="btn btn-outline-primary"> Batal </a>
      </form>
  </div>
{% endblock contents %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>
            {% block page_title %}
              
            {% endblock page_title %}
        </title>
        {% include "snippet/styles.html" %}
    </head>
    <body>

        {% include "snippet/navbar.html" %}
     
        <div class="container mt-2">
           {% block contents %}
             
           {% endblock contents %}
        </div>

        {% include "snippet/scripts.html" %}
    </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block page_title %}
    Home
{% endblock page_title %} 


{% block contents %}
    
        {% if user.is_authenticated %}
            <h2 class="mt-4 mb-4"> Welcome, {{ user.username }}. Thanks for logging in. </h2>
        {% else %}
            <h2 class="mt-4 mb-4"> Welcome, new user. Please log in. </h2>
        {% endif %}

        <div class="row">
    
        {% for artikel in latest_artikel_list  %}
            <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-body">
                <small>{{ artikel.kategori }}</small>
                <h4 class="card-title"><a href="{% url 'artikel:detail' artikel.slug %}"> {{ artikel.judul }} </a></h4>
                <small>{{ artikel.published }}</small>
                <hr>
                <small class="card-text">
                    {{ artikel.isi|truncatewords:30 }} 
                    <a href="{% url 'artikel:detail' artikel.slug %}"> Selengkapnya </a>
                </small>
                </div>
            </div>
            </div>
        {% endfor %}
    </div>
    


{% endblock contents %} 

templates/snippet/navbar.html
{% load static %}

   <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary ">
        <div class="container">
            <a class="navbar-brand" href="#">robikurniawan.com </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href=" {% url 'home' %} ">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=" {% url 'artikel:list' %}  ">Artikel</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Pricing</a>
                    </li>
                </ul>
                {% if user.is_authenticated %}

                <div class="nav-item dropdown ml-auto ">
                    <a class="nav-link dropdown-toggle text-light " href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'artikel:create' %}">Tambah Artikel </a>
                        <a class="dropdown-item" href="{% url 'artikel:manage' %}">Manage Artikel </a>
                        <a class="dropdown-item" href="{% url 'login:logout'  %}  "> Keluar  </a>
                    </div>
                </div>
                {% else %}

                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login:login'  %} ">Masuk  </a>
                    </li>
                </ul>

                {% endif %}
            
            </div>
        </div>
    </nav>
</header>

templates/snippet/scripts.html
{% load static %}

 <script src="{% static 'vendor/jquery/jquery-3.4.1.slim.min.js' %}"></script>
 <script src="{% static 'vendor/popper/popper.min.js' %}"></script>
 <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

templates/snippet/styles.html
{% load static %}

<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">